export const CATEGORIES_LIST_REQUEST = "CATEGORIES_LIST_REQUEST";
export const CATEGORIES_LIST_SUCCESSES = "CATEGORIES_LIST_SUCCESSES";
export const CATEGORIES_LIST_FAIL = "CATEGORIES_LIST_FAIL";

export const CATEGORIES_ADD_CATEGORY_REQUEST =
  "CATEGORIES_ADD_CATEGORY_REQUEST";
export const CATEGORIES_ADD_CATEGORY_SUCCESSES =
  "CATEGORIES_ADD_CATEGORY_SUCCESSES";
export const CATEGORIES_ADD_CATEGORY_FAIL = "CATEGORIES_ADD_CATEGORY_FAIL";

export const CATEGORIES_DELETE_CATEGORY_REQUEST =
  "CATEGORIES_DELETE_CATEGORY_REQUEST";
export const CATEGORIES_DELETE_CATEGORY_SUCCESSES =
  "CATEGORIES_DELETE_CATEGORY_SUCCESSES";
export const CATEGORIES_DELETE_CATEGORY_FAIL =
  "CATEGORIES_DELETE_CATEGORY_FAIL";
