export const ITEM_LIST_REQUEST = "ITEM_LIST_REQUEST";
export const ITEM_LIST_SUCCESSES = "ITEM_LIST_SUCCESSES";
export const ITEM_LIST_FAIL = "ITEM_LIST_FAIL";

export const ITEM_REQUEST = "ITEM_REQUEST";
export const ITEM_SUCCESSES = "ITEM_SUCCESSES";
export const ITEM_FAIL = "ITEM_FAIL";

export const ITEM_DELETE_REQUEST = "ITEM_DELETE_REQUEST";
export const ITEM_DELETE_SUCCESSES = "ITEM_DELETE_SUCCESSES";
export const ITEM_DELETE_FAIL = "ITEM_DELETE_FAIL";

export const ITEM_CREATE_REQUEST = "ITEM_CREATE_REQUEST";
export const ITEM_CREATE_SUCCESSES = "ITEM_CREATE_SUCCESSES";
export const ITEM_CREATE_FAIL = "ITEM_CREATE_FAIL";
export const ITEM_CREATE_RESET = "ITEM_CREATE_RESET";

export const ITEM_UPDATE_REQUEST = "ITEM_UPDATE_REQUEST";
export const ITEM_UPDATE_SUCCESSES = "ITEM_UPDATE_SUCCESSES";
export const ITEM_UPDATE_FAIL = "ITEM_UPDATE_FAIL";
export const ITEM_UPDATE_RESET = "ITEM_UPDATE_RESET";

export const ITEM_TOP_REQUEST = "ITEM_TOP_REQUEST";
export const ITEM_TOP_SUCCESSES = "ITEM_TOP_SUCCESSES";
export const ITEM_TOP_FAIL = "ITEM_TOP_FAIL";
