export const TABLES_INSIDE_REQUEST = "TABLES_INSIDE_REQUEST";
export const TABLES_INSIDE_SUCCESS = "TABLES_INSIDE_SUCCESS";
export const TABLES_INSIDE_FAIL = "TABLES_INSIDE_FAIL";
export const TABLES_OUTSIDE_REQUEST = "TABLES_OUTSIDE_REQUEST";
export const TABLES_OUTSIDE_SUCCESS = "TABLES_OUTSIDE_SUCCESS";
export const TABLES_OUTSIDE_FAIL = "TABLES_OUTSIDE_FAIL";
export const TABLES_AVAILABLE_UPDATE_REQUEST =
  "TABLES_AVAILABLE_UPDATE_REQUEST";
export const TABLES_AVAILABLE_UPDATE_SUCCESS =
  "TABLES_AVAILABLE_UPDATE_SUCCESS";
export const TABLES_AVAILABLE_UPDATE_FAIL = "TABLES_AVAILABLE_UPDATE_FAIL";

export const TABLES_BYID_REQUEST = "TABLES_BYID_REQUEST";
export const TABLES_BYID_SUCCESS = "TABLES_BYID_SUCCESS";
export const TABLES_BYID_FAIL = "TABLES_BYID_FAIL";

export const TABLES_ADD_REQUEST = "TABLES_ADD_REQUEST";
export const TABLES_ADD_SUCCESS = "TABLES_ADD_SUCCESS";
export const TABLES_ADD_FAIL = "TABLES_ADD_FAIL";
export const TABLES_ADD_RESET = "TABLES_ADD_RESET";

export const TABLES_UPDATE_REQUEST = "TABLES_UPDATE_REQUEST";
export const TABLES_UPDATE_SUCCESS = "TABLES_UPDATE_SUCCESS";
export const TABLES_UPDATE_FAIL = "TABLES_UPDATE_FAIL";
export const TABLES_UPDATE_RESET = "TABLES_UPDATE_RESET";

export const TABLES_DELETE_REQUEST = "TABLES_DELETE_REQUEST";
export const TABLES_DELETE_SUCCESS = "TABLES_DELETE_SUCCESS";
export const TABLES_DELETE_FAIL = "TABLES_DELETE_FAIL";
